name: invalidate-cloudfront

on:
  workflow_dispatch:
  repository_dispatch:
    types: [updated-cloudfront-app]

 
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  WEBAPP_STACK: ${{ secrets.WEBAPP_STACK }} 

jobs:
  invalidate-cloudfront-distribution:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: get-cloudfront-id
        run: | 
          CLOUDFRONT_ID=$(aws cloudformation describe-stacks --stack-name $WEBAPP_STACK --region eu-north-1 \
            --query "Stacks[0].Outputs[?OutputKey=='CloudFrontID'].OutputValue" --output text)
          
          echo "CLOUDFRONT_ID=$CLOUDFRONT_ID" >> "$GITHUB_ENV"
      - uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_REGION: "eu-north-1"
          DISTRIBUTION: ${{ env.CLOUDFRONT_ID }}
          PATHS: "/index.html"

